import { ChangeDetectionStrategy, Component } from '@angular/core';
import { NbIconLibraries } from '@nebular/theme';

@Component({
  selector: 'ngx-icons',
  styleUrls: ['./icons.component.scss'],
  templateUrl: './icons.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IconsComponent {

  evaIcons = [];

  constructor(iconsLibrary: NbIconLibraries) {
    this.evaIcons = Array.from(iconsLibrary.getPack('eva').icons.keys())
      .filter(icon => icon.indexOf('outline') === -1);

    iconsLibrary.registerFontPack('fa', { packClass: 'fa', iconClassPrefix: 'fa' });
    iconsLibrary.registerFontPack('far', { packClass: 'far', iconClassPrefix: 'fa' });
    iconsLibrary.registerFontPack('ion', { iconClassPrefix: 'ion' });
  }

  icons = {

    ionicons: [
      'add-circle-outline',
      'add-circle',
      'add',
      'airplane',
      'alarm',
      'albums',
      'alert',
      'american-football',
      'analytics',
      'aperture',
      'apps',
      'logo-apple-appstore',
      'archive',
      'arrow-back-outline',
      'arrow-back-circle-outline',
      'arrow-down-circle-outline',
      'arrow-down-outline',
      'arrow-forward',
      'arrow-up',
      'at',
      'attach',
      'backspace',
      'barcode',
      'baseball-outline',
      'basket',
      'basketball',
      'battery-charging',
      'battery-dead',
      'battery-full',
      'beaker',
      'bed',
      'beer',
      'bicycle',
      'bluetooth',
      'boat',
      'body',
      'bonfire',
      'book',
      'bookmark',
      'bookmarks',
      'color-filter-outline',
      'briefcase',
      'browsers',
      'brush',
      'bug',
      'build',
      'bulb',
      'bus',
      'business',
      'cafe',
      'calculator',
      'calendar',
      'call',
      'camera',
      'car',
      'card',
      'cart',
      'cash',
      'cellular',
      'chatbox',
      'chatbubbles',
      'checkbox-outline',
      'checkbox',
      'checkmark-circle-outline',
      'checkmark-circle',
      'checkmark',
      'clipboard',
      'alarm',
      'close-circle-outline',
      'close-circle',
      'close',
      'cloud-circle',
      'cloud-done',
      'cloud-download',
      'cloud-outline',
      'cloud-upload',
      'cloud',
      'cloudy-night',
      'cloudy',
      'code-download',
      'code-working',
      'code',
      'cog',
      'color-fill',
      'color-filter',
      'color-palette',
      'color-wand',
      'compass',
      'construct',
      'people',
      'people-outline',
      'people-circle-outline',
      'contrast',
      'copy',
      'create',
      'crop',
      'cube',
      'cut',
      'desktop',
      'disc',
      'document',
      'checkmark-done-outline',
      'download',
      'easel',
      'egg',
      'exit',
      'expand',
      'eye-off',
      'eye',
    ],

    fontAwesome: [
      'adjust', 'anchor', 'archive', 'chart-area', 'arrows-alt', 'arrows-alt-h',
      'arrows-alt-v', 'asterisk', 'at', 'car', 'ban', 'university',
      'chart-bar', 'barcode', 'bars', 'bed', 'beer',
      'bell', 'bell-slash', 'bicycle', 'binoculars',
      'birthday-cake', 'bolt', 'bomb', 'book', 'bookmark',
      'briefcase', 'bug', 'building', 'bullhorn',
    ],

    fontAwesomeRegular: [ 'chart-bar', 'bell', 'bell-slash', 'bookmark', 'building' ],
  };

}
