
export let FORM_INFO_PERSONA = {
    titulo: 'InfoPersona',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'InfoPersona',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label: 'Id*:',
        placeholder: 'Ej. Id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'PrimerNombre',
        label: 'PrimerNombre*:',
        placeholder: 'Ej. PrimerNombre',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'SegundoNombre',
        label: 'SegundoNombre*:',
        placeholder: 'Ej. SegundoNombre',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'PrimerApellido',
        label: 'PrimerApellido*:',
        placeholder: 'Ej. PrimerApellido',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'SegundoApellido',
        label: 'SegundoApellido*:',
        placeholder: 'Ej. SegundoApellido',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'FechaNacimiento',
        label: 'FechaNacimiento*:',
        placeholder: 'Ej. FechaNacimiento',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Usuario',
        label: 'Usuario*:',
        placeholder: 'Ej. Usuario',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Foto',
        label: 'Foto*:',
        placeholder: 'Ej. Foto',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'selectmultiple',
        claseGrid: 'col-6',
        nombre: 'TipoDiscapacidad',
        label: 'TipoDiscapacidad*:',
        placeholder: 'Ej. TipoDiscapacidad',
        requerido: true,
        tipo: 'TipoDiscapacidad',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'EstadoCivil',
        label: 'EstadoCivil*:',
        placeholder: 'Ej. EstadoCivil',
        requerido: true,
        tipo: 'EstadoCivil',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'GrupoEtnico',
        label: 'GrupoEtnico*:',
        placeholder: 'Ej. GrupoEtnico',
        requerido: true,
        tipo: 'GrupoEtnico',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Genero',
        label: 'Genero*:',
        placeholder: 'Ej. Genero',
        requerido: true,
        tipo: 'Genero',
        // key: 'Name',
        opciones: [],
    },
    ],
}
