clone:
  path: github.com/udistrital/campus_cliente

build:

  # build and test the go program
  nodejs:
    image: node:9.5.0
    commands:
     - apt-get update -y
     - mkdir directory_test
     - cd  directory_test
     - echo 'prueba rsync to S3' > test.txt
     - ls
     # - apt-get install -y zip
     # - npm install
     # - npm run lint:ci
     # - npm run build:prod

    when:
      branch: develop
      event: push

publish:

  # upload directory dist/ to s3 bucket
  s3_sync:
    region: "us-east-1"
    bucket: "drone-cliente-develop"
    access_key: $$DRONE_AWS_ACCESS_KEY_ID
    secret_key: $$DRONE_AWS_SECRET_ACCESS_KEY
    source:
    target: /campus_cliente-$$BRANCH
    delete: true
    when:
      branch: develop
      event: push

# publish:
#
#   # upload directory dist/ to s3 bucket
#   s3_sync:
#     region: "us-east-1"
#     bucket: "drone-cliente-develop"
#     access_key: $$DRONE_AWS_ACCESS_KEY_ID
#     secret_key: $$DRONE_AWS_SECRET_ACCESS_KEY
#     source: dist
#     target: /campus_cliente-$$BRANCH
#     delete: true
#     when:
#       branch: develop
#       event: push
#
# notify:
#
#   # notify telegram
#   webhook:
#     urls:
#       - https://api.telegram.org/bot$$DRONE_TELEGRAM_TOKEN/sendMessage
#     content_type: application/json
#     template: >
#       {
#         "chat_id": "-129350403",
#         "parse_mode": "Markdown",
#         "text": "`{{repo.full_name}}` [{{uppercase build.status}}]({{build.link_url}}) `{{build.branch}}`@{{truncate build.commit 7}}"
#       }
#     when:
#       branch: develop
#       event: push
