clone:
  path: github.com/udistrital/campus_cliente

build:

  # build and test the go program
  nodejs:
    image: node:9.5.0
    commands:
     - apt-get update -y
     - apt-get install -y zip
     - npm install -g grunt-cli bower
     - npm install
     - bower install --allow-root
     - grunt build
     - zip -r app.zip dist/

    when:
      branch: develop
      event: push

publish:

  # upload app.zip to s3 bucket for CodePipline
  s3:
    region: "us-east-1"
    bucket: "drone-helper-bucket"
    access_key: $$DRONE_AWS_ACCESS_KEY_ID
    secret_key: $$DRONE_AWS_SECRET_ACCESS_KEY
    source: app.zip
    target: /apps/campus_cliente-$$BRANCH.zip
    when:
      branch: develop
      event: push

# notify:
#
#   # notify telegram
#   webhook:
#     urls:
#       - https://api.telegram.org/bot$$DRONE_TELEGRAM_TOKEN/sendMessage
#     content_type: application/json
#     template: >
#       {
#         "chat_id": "-129350403",
#         "parse_mode": "Markdown",
#         "text": "`{{repo.full_name}}` [{{uppercase build.status}}]({{build.link_url}}) `{{build.branch}}`@{{truncate build.commit 7}}"
#       }
#     when:
#       branch: develop
#       event: push
