
export let FORM_INFORMACION_CONTACTO = {
    titulo: 'InformacionContacto',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'InformacionContacto',
    campos: [
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'PaisResidencia',
        label_i18n: 'pais_residencia',
        placeholder_i18n: 'pais_residencia',
        requerido: true,
        tipo: 'Lugar',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'CiudadResidencia',
        label_i18n: 'ciudad_residencia',
        placeholder_i18n: 'ciudad_residencia',
        requerido: true,
        tipo: 'Lugar',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'DireccionResidencia',
        label_i18n: 'direccion_residencia',
        placeholder_i18n: 'direccion_residencia',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'EstratoResidencia',
        label_i18n: 'estrato_residencia',
        placeholder_i18n: 'estrato_residencia',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'CodigoPostal',
        label_i18n: 'codigo_postal',
        placeholder_i18n: 'codigo_postal',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Telefono',
        label_i18n: 'telefono',
        placeholder_i18n: 'telefono',
        requerido: true,
        tipo: 'text',
    },
    ],
}
