export let FORM_IDIOMAS = {
  // titulo: 'Idiomas',
  tipo_formulario: 'mini',
  alertas: true,
  btn: 'Guardar',
  modelo: 'InfoIdioma',
  campos: [
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Idioma',
      label_i18n: 'idioma',
      placeholder_i18n: 'idioma',
      requerido: true,
      tipo: 'text',
      key: 'Nombre',
      opciones: [],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'IdiomaNativo',
      label_i18n: 'idioma_nativo_pregunta',
      placeholder_i18n: 'idioma_nativo',
      requerido: true,
      tipo: 'text',
      key: 'valor',
      opciones: [
        { Id: 1, valor: 'Si' },
        { Id: 2, valor: 'No' },
      ],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
      nombre: 'NivelEscritura',
      label_i18n: 'nivel_escritura',
      placeholder_i18n: 'nivel_escritura',
      requerido: true,
      tipo: 'text',
      key: 'valor',
      opciones: [
          { Id: 1, valor: 'Alto' },
          { Id: 2, valor: 'Medio' },
          { Id: 3, valor: 'Bajo' },
      ],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
      nombre: 'NivelEscucha',
      label_i18n: 'nivel_escucha',
      placeholder_i18n: 'nivel_escucha',
      requerido: true,
      tipo: 'text',
      key: 'valor',
      opciones: [
          { Id: 1, valor: 'Alto' },
          { Id: 2, valor: 'Medio' },
          { Id: 3, valor: 'Bajo' },
      ],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
      nombre: 'NivelHabla',
      label_i18n: 'nivel_habla',
      placeholder_i18n: 'nivel_habla',
      requerido: true,
      tipo: 'text',
      key: 'valor',
      opciones: [
          { Id: 1, valor: 'Alto' },
          { Id: 2, valor: 'Medio' },
          { Id: 3, valor: 'Bajo' },
      ],
    },
    {
      etiqueta: 'select',
      claseGrid: 'col-lg-3 col-md-6 col-sm-12 col-xs-12',
      nombre: 'NivelLectura',
      label_i18n: 'nivel_lectura',
      placeholder_i18n: 'nivel_lectura',
      requerido: true,
      tipo: 'text',
      key: 'valor',
      opciones: [
          { Id: 1, valor: 'Alto' },
          { Id: 2, valor: 'Medio' },
          { Id: 3, valor: 'Bajo' },
      ],
    },
  ],
}
