export let FORM_EXPERIENCIA_LABORAL = {
  // titulo: 'ExperienciaLaboral',
  tipo_formulario: 'mini',
  alertas: true,
  btn: 'Guardar',
  modelo: 'InfoExperienciaLaboral',
  campos: [
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'NombreEmpresa',
      label_i18n: 'nombre_empresa',
      placeholder_i18n: 'nombre_empresa',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'DireccionEmpresa',
      label_i18n: 'direccion_empresa',
      placeholder_i18n: 'direccion_empresa',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'CorreoEmpresa',
      label_i18n: 'correo_empresa',
      placeholder_i18n: 'correo_empresa',
      requerido: true,
      tipo: 'email',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TelefonoEmpresa',
      label_i18n: 'telefono_empresa',
      placeholder_i18n: 'telefono_empresa',
      requerido: true,
      tipo: 'number',
      minimo: 1000,
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
      nombre: 'AnioInicio',
      label_i18n: 'anio_inicio',
      placeholder_i18n: 'anio_inicio',
      requerido: true,
      tipo: 'number',
      minimo: 1900,
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-3 col-md-3 col-sm-12 col-xs-12',
      nombre: 'AnioFin',
      label_i18n: 'anio_fin',
      placeholder_i18n: 'anio_fin',
      requerido: true,
      tipo: 'number',
      minimo: 1900,
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoVinculacion',
      label_i18n: 'tipo_vinculacion',
      placeholder_i18n: 'tipo_vinculacion',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'TipoDedicacion',
      label_i18n: 'tipo_dedicacion',
      placeholder_i18n: 'tipo_dedicacion',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-6 col-md-6 col-sm-12 col-xs-12',
      nombre: 'Cargo',
      label_i18n: 'cargo',
      placeholder_i18n: 'cargo',
      requerido: true,
      tipo: 'text',
    },
    {
      etiqueta: 'input',
      claseGrid: 'col-lg-12 col-md-12 col-sm-12 col-xs-12',
      nombre: 'DescripcionCargo',
      label_i18n: 'descripcion_cargo',
      placeholder_i18n: 'descripcion_cargo',
      requerido: true,
      tipo: 'text',
    },
  ],
}
