
export let FORM_LUGAR_UBICACION = {
    titulo: 'LugarUbicacion',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'LugarUbicacion',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label_i18n: 'id',
        placeholder_i18n: 'id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Lugar',
        label_i18n: 'lugar',
        placeholder_i18n: 'lugar',
        requerido: true,
        tipo: 'Lugar',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Direccion',
        label_i18n: 'direccion',
        placeholder_i18n: 'direccion',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'CodigoPostal',
        label_i18n: 'codigo_postal',
        placeholder_i18n: 'codigo_postal',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Estrato',
        label_i18n: 'estrato',
        placeholder_i18n: 'estrato',
        requerido: true,
        tipo: 'number',
    },
    ],
}
