export const COSMIC_THEME = {
  name: 'cosmic',
  base: 'default',
  variables: {
    tempColorGreen: '#7bff24',
    tempColorLightBlue: '#31ffad',
    tempColorBlue: '#2ec7fe',
    tempColorYellow: '#fff024',
    tempColorOrange: '#f7bd59',

    solarColorDarkGreen: '#19977E',
    solarColorShadow: 'rgba(0, 217, 119, 0.3)',
    trafficColorBlack: '#000000',
    trafficTooltipBg: 'rgba(0, 255, 170, 0.35)',
    trafficLineBg: 'rgba(146, 141, 255, 0.5)',
    trafficShadowLineBg: '#bdbaff',
    trafficShadowLineDarkBg: '#a695ff',
    trafficShadowLineShadow: 'rgba(33, 7, 77, 0.5)',
    trafficGradFrom: 'rgba(118, 89, 255, 0.4)',
    trafficGradTo: 'rgba(164, 84, 255, 0.5)',

    electricityAxisColor: '#a1a1e5',
    electricityLineGradFrom: '#00ffaa',
    electricityLineGradTo: '#fff835',
    electricityLineShadow: 'rgba(14, 16, 48, 0.4)',
    electricityAreaGradFrom: 'rgba(188, 92, 255, 0.5)',
    electricityAreaGradTo: 'rgba(188, 92, 255, 0)',

    bubbleMapTitleColor: '#ffffff',
    bubbleMapGeoColor1: '#e6b045',
    bubbleMapGeoColor2: '#0088ff',
    bubbleMapGeoColor3: '#ff386a',
    bubbleMapGeoColor4: '#00d977',
    bubbleMapGeoColor5: '#7659ff',
    bubbleMapGeoColor6: '#24dec8',
    bubbleMapAreaColor: '#2c2961',
    bubbleMapAreaHoverColor: '#a1a1e5',
    bubbleMapAreaBorderColor: '#654ddb',

    echartsBackgroundColor: '#363175',

    echartsPieColor1: 'rgb(168, 56, 93)',
    echartsPieColor2: 'rgb(122, 163, 229)',
    echartsPieColor3: 'rgb(170, 227, 245)',
    echartsPieColor4: 'rgb(173, 205, 237)',
    echartsPieColor5: 'rgb(162, 126, 168)',
    echartsPieLegendTextColor: 'white',
    echartsPieItemHoverShadowColor: 'rgba(0, 0, 0, 0.5)',

    echartsBarColor1: '#3398DB',
    echartsBarXAxisLineColor: 'white',
    echartsBarYAxisLineColor: 'white',

    echartsLineColor1: 'red',
    echartsLineColor2: 'black',
    echartsLineColor3: 'white',
    echartsLineLegendTextColor: 'white',
    echartsLineXAxisLineColor: 'white',
    echartsLineYAxisLineColor: 'white',

    echartsMultipleXAxisColor1: '#5793f3',
    echartsMultipleXAxisColor2: '#d14a61',
    echartsMultipleXAxisColor3: '#675bba',
    echartsMultipleXAxisLegendTextColor: 'white',
    echartsMultipleXAxisYAxisLineColor: 'white',

    echartsAreaStackColor1: 'red',
    echartsAreaStackColor2: 'blue',
    echartsAreaStackColor3: 'purple',
    echartsAreaStackColor4: 'yellow',
    echartsAreaStackColor5: 'pink',
    echartsAreaStackLegendTextColor: 'white',
    echartsAreaStackXAxisLineColor: 'white',
    echartsAreaStackYAxisLineColor: 'white',
    echartsAreaStackTooltipBackgroundColor: '#6a7985',

    echartsBarAnimationColor1: 'red',
    echartsBarAnimationColor2: 'white',
    echartsBarAnimationLegendTextColor: 'white',
    echartsBarAnimationXAxisLineColor: 'white',
    echartsBarAnimationYAxisLineColor: 'white',

    echartsRadarColor1: 'red',
    echartsRadarColor2: 'white',
    echartsRadarLegendTextColor: 'white',
    echartsRadarNameTextColor: 'white',
    echartsRadarSplitAreaStyleColor: 'transparent',

    chartjsPieXAxisColor: 'rgba(148,159,177,1)',
    chartjsPieYAxisColor: 'rgba(148,159,177,1)',
    chartjsPieTickColor: 'white',
    chartjsPieLegendTextColor: 'white',

    chartjsBarXAxisColor: 'rgba(148,159,177,1)',
    chartjsBarYAxisColor: 'rgba(148,159,177,1)',
    chartjsBarTickColor: 'white',
    chartjsBarLegendTextColor: 'white',

    chartjsLineXAxisColor: 'rgba(148,159,177,1)',
    chartjsLineYAxisColor: 'rgba(148,159,177,1)',
    chartjsLineTickColor: 'white',
    chartjsLineLegendTextColor: 'white',

    chartjsMultipleXAxisXAxisColor: 'rgba(148,159,177,1)',
    chartjsMultipleXAxisYAxisColor: 'rgba(148,159,177,1)',
    chartjsMultipleXAxisTickColor: 'white',
    chartjsMultipleXAxisLegendTextColor: 'white',

    chartjsBarHorizontalColor1: 'red',
    chartjsBarHorizontalColor2: 'blue',
    chartjsBarHorizontalXAxisColor: 'rgba(148,159,177,1)',
    chartjsBarHorizontalYAxisColor: 'rgba(148,159,177,1)',
    chartjsBarHorizontalTickColor: 'white',
    chartjsBarHorizontalLegendTextColor: 'white',

    chartjsRadarColor1: 'red',
    chartjsRadarColor2: 'blue',
    chartjsRadarLegendTextColor: 'white',
    chartjsRadarScaleGridLinesColor: 'white',
    chartjsRadarScaleAngleLinesColor: 'white',
    chartjsRadarPointLabelFontColor: 'white',
  },
};
