
export let FORM_PERSONA = {
  titulo: 'Datos Basicos',
  tipo_formulario: 'basic',
  btn: 'Guardar',
  alertas: true,
  btnLimpiar: 'Salir',
  modelo: 'Persona',
  campos: [{
      etiqueta: 'input',
      claseGrid : 'col-6',
      nombre: 'PrimerNombre',
      label: 'Primer nombre*:',
      placeholder: 'Ej. Jose',
      requerido: true,
      tipo: 'text',
      },{
        etiqueta: 'input',
        claseGrid : 'col-6',
        nombre: 'SegundoNombre',
        label: 'Segundo nombre:',
        placeholder: 'Ej. Steven',
        requerido: false,
        tipo: 'text',
    },{
      etiqueta: 'input',
      claseGrid : 'col-6',
      nombre: 'PrimerApellido',
      label: 'Primer apellido*:',
      placeholder: 'Ej. Rodriguez',
      requerido: true,
      tipo: 'text',
    }, {
      etiqueta: 'input',
      claseGrid : 'col-6',
      nombre: 'SegundoApellido',
      label: 'Segundo apellido:',
      placeholder: 'Ej. Perez',
      requerido: false,
      tipo: 'text',
    },{
        claseGrid : 'col-4',
        etiqueta: 'select',
        nombre: 'PaisNacimiento',
        label: 'País de nacimiento*:',
        requerido: true,
        valor: { Id: 0 },
        opciones: [
            { Id: 0, valor: 'Seleccione su país de nacimiento ...' },
            { Id: 1, valor: 'Perú' },
            { Id: 2, valor: 'Chile' },
            { Id: 3, valor: 'Colombia' },
            { Id: 4, valor: 'Rusia' },
        ],
    }, {
        claseGrid : 'col-4',
        etiqueta: 'select',
        nombre: 'CiudadNacimiento',
        label: 'Ciudad de nacimiento*:',
        requerido: true,
        valor: { Id: 0 },
        opciones: [
            { Id: 0, valor: 'Seleccione su ciudad de nacimiento ...' },
            { Id: 1, valor: 'AAA' },
            { Id: 2, valor: 'BBB' },
            { Id: 3, valor: 'CCC' },
            { Id: 4, valor: 'DDD' },
        ],
    },{
      etiqueta: 'input',
      claseGrid : 'col-4',
      nombre: 'FechaNacimiento',
      label: 'Fecha de nacimiento*:',
      placeholder: 'Ej. 01/01/2010',
      requerido: true,
      tipo: 'date',
    }],
}
