export const REDUCER_LIST = {
    Genero: 'listGenero',
    ClasificacionNivelIdioma: 'listClasificacionNivelIdioma',
    EstadoAdmision: 'listEstadoAdmision',
    EstadoCivil: 'listEstadoCivil',
    GrupoEtnico: 'listGrupoEtnico',
    Idioma: 'listIdioma',
    LineaInvestigacion: 'listLineaInvestigacion',
    Pais: 'listPais',
    Ciudad: 'listCiudad',
    Lugar: 'listLugar',
    Metodologia: 'listMetodologia',
    NivelFormacion: 'listNivelFormacion',
    NivelIdioma: 'listNivelIdioma',
    ProgramaAcademico: 'listProgramaAcademico',
    TipoContacto: 'listTipoContacto',
    TipoDiscapacidad: 'listTipoDiscapacidad',
    TipoLugar: 'listTipoLugar',
    Titulacion: 'listTitulacion',
    TipoIdentificacion: 'listTipoIdentificacion',
};
